name: tagesausflug nrw
favicon: null
layout_spectrum: 0.3914605507161468
typography_spectrum: 0.004864430287852883
title: Ausflugstipps für Nordrhein Westfalen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7751464431639761
  lightness: 0.9742370992898941
  saturation: 0.2826359432656318
  rhythmicContrast: 0.6470369882881641
purpose: []
